title: "COVID-19 in data: How bad is it?"
show_dir_listing: TRUE
markdown: kramdown
footnote_nr: 72

plugins:
  - "jekyll-github-metadata"

#theme: jekyll-theme-minimal

# plugins:
#   - jekyll-remote-theme

# remote_theme: mmistakes/minimal-mistakes
